// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP_4UjNKZRYDzkY7I7o6EAnpQCKJnzazY',
    appId: '1:181705743814:web:b86e83be1a8624ffe326c7',
    messagingSenderId: '181705743814',
    projectId: 'lms-flutter-app-10',
    authDomain: 'lms-flutter-app-10.firebaseapp.com',
    storageBucket: 'lms-flutter-app-10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe-NY5-LPttUEzIVW1fV6SHXZBYhgB8GU',
    appId: '1:181705743814:android:314b004590b4c96de326c7',
    messagingSenderId: '181705743814',
    projectId: 'lms-flutter-app-10',
    storageBucket: 'lms-flutter-app-10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4G3iG_9qNYuTfbC3oWt9XjrxN3Z_vrnA',
    appId: '1:181705743814:ios:10d623e079f97d77e326c7',
    messagingSenderId: '181705743814',
    projectId: 'lms-flutter-app-10',
    storageBucket: 'lms-flutter-app-10.firebasestorage.app',
    iosBundleId: 'com.example.lmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4G3iG_9qNYuTfbC3oWt9XjrxN3Z_vrnA',
    appId: '1:181705743814:ios:10d623e079f97d77e326c7',
    messagingSenderId: '181705743814',
    projectId: 'lms-flutter-app-10',
    storageBucket: 'lms-flutter-app-10.firebasestorage.app',
    iosBundleId: 'com.example.lmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP_4UjNKZRYDzkY7I7o6EAnpQCKJnzazY',
    appId: '1:181705743814:web:27f8bafc207e608ee326c7',
    messagingSenderId: '181705743814',
    projectId: 'lms-flutter-app-10',
    authDomain: 'lms-flutter-app-10.firebaseapp.com',
    storageBucket: 'lms-flutter-app-10.firebasestorage.app',
  );
}
